### ISSUE TITLE
Pup is retarded

### ISSUE THREAD

**Issue by HypseHere** [Hanafudas/cat-fun-page#1]
pup you ape, hurry up and add me on discord, i need to talk to you about shit
Hypse#1650

**Comment by Hanafudas** [comment]
okay. I tried adding you and it didnt recognise it as a user send it again or add me.
- Pup#6112

**Comment by Hanafudas** [comment]
> pup you ape, hurry up and add me on discord, i need to talk to you about shit Hypse#1650

okay. I tried adding you and it didnt recognise it as a user send it again or add me.

Pup#6112
